name       : libcaca
version    : 0.99.19
release    : 2
source     :
    - http://caca.zoy.org/files/libcaca/libcaca-0.99.beta19.tar.gz : 128b467c4ed03264c187405172a4e83049342cc8cc2f655f53a2d0ee9d3772f4
license    : WTFPL
component  : multimedia.library
summary    : libcaca is a graphics library
description: |
    libcaca is a graphics library that outputs text instead of pixels, so that it can work on older video cards or text terminals.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(ftgl)
    - pkgconfig(imlib2)
    - pkgconfig(x11)
    - pkgconfig(pangoft2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
